
de{
  try{
  stage('Checkout'){
    git 'https://mAyman2612@bitbucket.org/mAyman2612/nodejs-endpoint-container.git'

  }
  // to run tests, istall those packes on you system
  /* #  curl --silent --location https://rpm.nodesource.com/setup_8.x | sudo bash
    # yum install -y nodejs
    # yum install npm 
    # npm install -g mocha
    */
    
  
  stage('RUN Unit Tests'){
      sh "npm install"
      sh "npm test"
  }
  stage('Docker Build, Push'){
    withDockerRegistry([credentialsId: '2dfd9d0d-a300-49ee-aaaf-0a3efcaa5279', url: 'https://index.docker.io/v1/']) {
      sh "docker build -t mohamedayman/nodejs-demo ."
      sh "docker push mohamedayman/nodejs-demo"
        }

    }
    
   stage('Deploy nodejs App'){
       sh "docker rm -f myapp"
       sh "docker run --name myapp -d -p 80:3000 mohamedayman/nodejs-demo "
   }
     } catch (err) {
      currentBuild.result = 'FAILURE'
    }
}

